### ISSUE TITLE
Cannot Access Instagram

### ISSUE THREAD

**Issue by kevincfz** [SteamedFish/gfwiplist#1]
I could not successfully connect to Instagram using the current routes, possibly due to the new block on Instagram.

**Comment by SteamedFish** [comment]
Instagram don't have any IP address themselves. Instead they use several different CDN's and other hosting services like Amazon cloudfront, akamai amazon EC2, Facebook, etc.
1. I'll update amazon EC2's IP blocks. amazon officially provides all their EC2 IP blocks. It'll be an easy thing to to.
2. Collect akamai IP blocks will almost be an impossible thing to do. They don't officially provides their IP blocks. ASNs akamai is broadcasting includes more than 4000 IP blocks.
3. The Facebook IP blocks Instagram is using seems already in the list.

Unfortunately all the real photos stored in akamai.

**Comment by SteamedFish** [comment]
EC2 IP blocks updated. I'll testing tonight to see if Instagram's main website (not photos unfortunately) can be accessed.

**Comment by kevincfz** [comment]
Thanks a lot I appreciated it!

**Comment by kevincfz** [comment]
Is there any update on this? why is this labeled wontfix ?

**Comment by SteamedFish** [comment]
Instagram has changed to use https. It's no longer get blocked.
