### ISSUE TITLE
ios app store and kindle

### ISSUE THREAD

**Issue by coldrook** [SteamedFish/gfwiplist#3]
apple  IP 导致所有app无法升级，只能进入store，去除后一切正常
kindle paperwhite无法同步，目前无法判断是什么IP段导致的

**Comment by SteamedFish** [comment]
Kindle paperwhite 应该是 amazon 的。

我这边这些都是没问题的，比较奇怪，能定位到是什么原因导致的失败么？

**Comment by coldrook** [comment]
不是Amazon的问题，国内推送太慢了，要开shadowsocks才行
